### ISSUE TITLE
Facebook Graph API not Return First & Last Names

### ISSUE THREAD

**Issue by rhamilton281** [OutoftheCoop/CoopOauth#1]
I'm assuming Facebook changed their API at some point and first name and last name are no longer returned - only a 'name' field. 

Issue occurs at line 31 in FacebookGraphApi.cs

**Comment by LJNielsenDk** [comment]
I just spent a while figuring out this is why it doesn't work for me, so it should be noted that this breaks login and results in this error:

> An error occurred. Value cannot be null. Parameter name: name at Umbraco.Core.Mandate.That[TException](Boolean condition, Func`1 defer) at Umbraco.Core.Mandate.ParameterNotNullOrEmpty(String value, String paramName) at Umbraco.Core.Models.Member..ctor(String name, String email, String username, IMemberType contentType) at Umbraco.Core.Services.MemberService.CreateMember(String username, String email, String name, IMemberType memberType) at Umbraco.Core.Services.MemberService.CreateMember(String username, String email, String name, String memberTypeAlias) at CoopRelay.Relay.Member.Create(String username, String password, String email, String name, String memberTypeAlias, NameValueCollection properties) at CoopOauth.OauthMemberRepository.Create(OauthMember m) at CoopOauth.OauthMemberRepository.Checkin(OauthMember m) at CoopOauth.Controllers.OauthSurfaceController.Login(OauthRequest model, OauthProviderBase provider, String returnUrl)

because of the line `Name = data.FirstName + " " + data.LastName,` in OauthProviderBase.Get(OauthRequest request).

It appears that the combined name field is already provided by facebook and is named `name` in Graph API v2.4 and up.

It seems the API version in CoopOauth is overridden by the one in the Facebook App registration and I have that set to v2.5.

Facebook does not allow downgrading API versions of apps to lower than what they were when the app was registered. This makes this plugin useless to all apps created after Graph API v2.3 until this is fixed. At the time of writing v2.5 is the current version.

**Comment by AkiDK** [comment]
In order to get it working you have to download the CoopOauth and recompile the dll 
In the FacebookGraphApi you need to add these parameters...  
fields=first_name,last_name
The full url is this... 
`var url = string.Format("https://graph.facebook.com/me?fields=first_name,last_name&access_token={0}",`

After that it works...
